apiVersion: v2
name: prometheus
type: application
version: "2.1.0"
appVersion: "v2.48.1"
description: A Helm chart to install Prometheus based on Prometheus Operator
home: https://prometheus.io/
sources:
  - https://github.com/prometheus/prometheus
  - https://github.com/neticdk/k8s-oaas-observability
keywords:
- prometheus
maintainers:
  - name: langecode
    email: tal@netic.dk
