apiVersion: v2
name: prometheus-operator
type: application
description: A Helm chart to install Prometheus Operator
home: https://git.netic.dk/projects/PD/repos/charts/browse
version: "1.0.1"
appVersion: "0.42.0"
maintainers:
- name: Thor Anker Kvisg√•rd Lange
  email: tal@netic.dk
